apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server

    spec:
      containers:
        - name: server
          image: lusamdebonfils/server:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: service-api-key
            - name: USER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: userService
            - name: USER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-config
                  key: userServicePort