apiVersion: v1
kind: Service
metadata:
  name: rmtpserver
spec:
  type: LoadBalancer
  selector:
    app: rmtpserver
  # ports:
  #   - port: 9090
  #     targetPort: 1935
  ports:
    - name: apiport
      protocol: TCP
      port: 3333
      targetPort: 3333
    - name: rtmpport
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: streamport 
      protocol: TCP
      port: 8888
      targetPort: 8888