apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmtpserver-deployment
  labels:
    app: rmtpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmtpserver
  template:
    metadata:
      labels:
        app: rmtpserver

    spec:
      containers:
        - name: rmtpserver
          image: timnuwa/rmtpserver:latest
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["gcsfuse","--key-file", "/usr/src/app/stream-259020-firebase-adminsdk-z0kuq-cc9d2f5021.json","--implicit-dirs", "stream-259020.appspot.com", "/mnt/data"]
            preStop:
              exec:
                command: ["fusermount", "-u", "/mnt/data"]
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: rmtpserver-config
                  key: someKey1
            